pub mod login;
pub mod register;
pub mod home;
pub mod profile;
pub mod deposit;
pub mod transfer;
pub mod transactions;
pub mod insights;
pub mod not_found;

pub use login::LoginPage;
pub use register::RegisterPage;
pub use home::HomePage;
pub use profile::ProfilePage;
pub use deposit::DepositPage;
pub use transfer::TransferPage;
pub use transactions::TransactionsPage;
pub use insights::InsightsPage;
pub use not_found::NotFoundPage;
